name: Deploy upload-service

on:
  push:
    branches: [main] # deploy every merge to main
  workflow_dispatch: # …or on-demand from the Actions tab

permissions: # required for OIDC
  id-token: write
  contents: read

env:
  # Change to the AWS account + region where you bootstrapped CDK
  AWS_REGION: us-east-1
  # Optional: disable CDK’s “Are you sure?” prompts in CI
  CI: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # ---------- Authenticate to AWS via GitHub-→AWS OIDC ----------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------- TypeScript compile & synth ----------
      - name: Build (tsc)
        run: npm run build

      # Optional: run unit tests if you have them
      # - name: npm test
      #   run: npm test

      # ---------- Deploy ----------
      - name: CDK deploy (auto-approve)
        run: npx cdk deploy --all --require-approval never
